name: Create lists

on:
  push:
    branches: [ "main" ]
    paths:
      - .github/workflows/create-lists.yml
      - update.py
      - extras.lst
  schedule:
    - cron: '29 */8 * * *'

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4.1.4
    - name: Generate lists
      uses: actions/setup-python@v5.1.0
      with:
        python-version: '3.10' 
    - run: |
        python  update.py
    
    - name: Push lists
      uses: EndBug/add-and-commit@v9
      with:
        add: 'inside-dnsmasq-nfset.lst'
        author_name: GitHub Action
        author_email: githubaction@githubaction.com
        message: 'Update lists'
        push: true
